/* ================================================================
   PODPAHH — Store Engine (static)
   Carrinho localStorage + Age Gate + Wishlist + Checkout WhatsApp
   Sem dependências. Carregar em todas as páginas.
   ================================================================ */
(function () {
  'use strict';

  /* ---------------- CONFIG ---------------- */
  var CFG = {
    // WhatsApp de checkout (55 + DDD + número, só dígitos)
    whatsapp: '5547999453628',
    maxQty: 99,
    ageKey: 'podpahh_age_ok',
    cartKey: 'podpahh_cart_v1',
    catKey: 'podpahh_catalog_v1',
    wishKey: 'podpahh_wishlist_v1'
  };

  var $ = function (s, r) { return (r || document).querySelector(s); };
  var $$ = function (s, r) { return Array.prototype.slice.call((r || document).querySelectorAll(s)); };

  function money(v) {
    return 'R$ ' + v.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  function parsePrice(txt) {
    // "R$ 1.234,56" -> 1234.56
    var m = (txt || '').replace(/[^\d,\.]/g, '');
    var parts = m.split(',');
    var intPart = parts.length > 1 ? parts[0] : m;
    intPart = intPart.replace(/\./g, '');
    var dec = parts.length > 1 ? parts[1] : '00';
    var v = parseFloat(intPart + '.' + dec.slice(0, 2));
    return isNaN(v) ? 0 : v;
  }
  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function base() {
    return (document.body.getAttribute('data-base') || '.');
  }
  function safeId(s) {
    return String(s).replace(/[^A-Za-z0-9_-]/g, '');
  }
  function url(p) {
    if (!p) return p;
    if (/^(https?:|#|mailto:|data:)/.test(p)) return p;
    if (p.indexOf('assets/') === 0 || p.indexOf('produto/') === 0) return base() + '/' + p;
    return p;
  }

  /* ---------------- CATALOG (global file + scraped cards) ---------------- */
  function loadCatalog() {
    var cat = {};
    // 1) global catalog generated by cleanup script (authoritative)
    if (window.PODPAHH_CATALOG) {
      for (var k in window.PODPAHH_CATALOG) cat[k] = window.PODPAHH_CATALOG[k];
    }
    // 2) merge products managed by Admin Panel (server local / Supabase)
    if (window.PODPAHH_ADMIN_PRODUCTS) {
      for (var a in window.PODPAHH_ADMIN_PRODUCTS) cat[a] = window.PODPAHH_ADMIN_PRODUCTS[a];
    }
    // 3) merge persisted scrape
    try {
      var saved = JSON.parse(localStorage.getItem(CFG.catKey)) || {};
      for (var s in saved) if (!cat[s]) cat[s] = saved[s];
    } catch (e) {}
    return cat;
  }
  function saveCatalog(cat) {
    try { localStorage.setItem(CFG.catKey, JSON.stringify(cat)); } catch (e) {}
  }
  function scrapeCards() {
    var cat = loadCatalog();
    var changed = false;
    $$('.pcard').forEach(function (card) {
      var id = (card.id || '').replace('pcard-', '');
      if (!id || cat[id]) return; // global catalog wins
      var nameEl = $('.pcard-name', card);
      var priceEl = $('.pcard-price', card);
      var img = $('img', card);
      var link = $('a.pcard-img, a.pcard-name', card) || $('a', card);
      var brandEl = $('.pcard-brand', card);
      cat[id] = {
        name: nameEl ? nameEl.textContent.trim() : 'Produto',
        price: priceEl ? parsePrice(priceEl.textContent) : 0,
        img: img ? (img.getAttribute('data-src') || img.getAttribute('src') || '') : '',
        url: link ? link.getAttribute('href') : '',
        brand: brandEl ? brandEl.textContent.trim() : ''
      };
      changed = true;
    });
    if (changed) saveCatalog(cat);
    return cat;
  }

  /* ---------------- CART STATE ---------------- */
  function loadCart() {
    try { return JSON.parse(localStorage.getItem(CFG.cartKey)) || {}; }
    catch (e) { return {}; }
  }
  function saveCart(cart) {
    try { localStorage.setItem(CFG.cartKey, JSON.stringify(cart)); } catch (e) {}
    renderAll();
  }
  function cartCount(cart) {
    var n = 0; for (var k in cart) n += cart[k].qty; return n;
  }
  function cartSubtotal(cart) {
    var cat = loadCatalog(), s = 0;
    for (var k in cart) {
      var p = cat[k]; if (p) s += p.price * cart[k].qty;
    }
    return s;
  }

  /* ---------------- PUBLIC API (onclick handlers no HTML) ---------------- */
  window.vsAddToCart = function (id, btn) {
    var cat = loadCatalog();
    var p = cat[id];
    if (!p) { // página sem o card? tenta achar em outro lugar
      cat = scrapeCards(); p = cat[id];
    }
    if (!p) return;
    var cart = loadCart();
    cart[id] = cart[id] || { qty: 0 };
    cart[id].qty = Math.min(cart[id].qty + 1, CFG.maxQty);
    saveCart(cart);
    if (btn) {
      var old = btn.innerHTML;
      btn.innerHTML = '<i class="fa fa-check"></i>ADICIONADO';
      btn.style.background = 'linear-gradient(135deg,#00c853,#00e676)';
      setTimeout(function () { btn.innerHTML = old; btn.style.background = ''; }, 1200);
    }
    toggleCart(true);
  };

  window.vsOpenCart = function () { toggleCart(true); };
  window.vsCloseCart = function () { toggleCart(false); };

  window.vsQty = function (id, delta) {
    var cart = loadCart();
    if (!cart[id]) return;
    cart[id].qty += delta;
    if (cart[id].qty <= 0) delete cart[id];
    saveCart(cart);
  };

  window.vsRemoveItem = function (id) {
    var cart = loadCart();
    delete cart[id];
    saveCart(cart);
  };

  window.vsToggleWish = function (id, btn) {
    var wish = loadWish();
    if (wish[id]) { delete wish[id]; if (btn) btn.classList.remove('on'); }
    else { wish[id] = 1; if (btn) btn.classList.add('on'); }
    try { localStorage.setItem(CFG.wishKey, JSON.stringify(wish)); } catch (e) {}
    renderWishCount();
    // Sincroniza com a conta (favoritos persistem entre aparelhos).
    // O localStorage continua como cache imediato; o servidor é a verdade.
    try {
      var token = getSessionToken();
      if (token && window.PodpahhDB && window.PodpahhDB.toggleWishlist) {
        window.PodpahhDB.toggleWishlist(String(id), '', token).catch(function () {});
      }
    } catch (e) {}
  };

  /* ---------------- WISHLIST ---------------- */
  function loadWish() {
    try { return JSON.parse(localStorage.getItem(CFG.wishKey)) || {}; }
    catch (e) { return {}; }
  }
  function renderWishCount() {
    var n = Object.keys(loadWish()).length;
    $$('.wish-count').forEach(function (el) {
      el.textContent = n;
      el.style.display = n ? '' : 'none';
    });
  }
  // Puxa os favoritos da conta e mescla no cache local (união).
  function syncWishlistFromServer() {
    try {
      var token = getSessionToken();
      if (!token || !window.PodpahhDB || !window.PodpahhDB.getWishlist) return;
      window.PodpahhDB.getWishlist(token).then(function (res) {
        if (!res || !res.success || !res.data) return;
        var wish = loadWish(), changed = false;
        res.data.forEach(function (w) {
          var pid = w && (w.product_id || w.id);
          if (pid && !wish[pid]) { wish[pid] = 1; changed = true; }
        });
        if (changed) {
          try { localStorage.setItem(CFG.wishKey, JSON.stringify(wish)); } catch (e) {}
          renderWishCount();
        }
      }).catch(function () {});
    } catch (e) {}
  }

  /* ---------------- DRAWER RENDER ---------------- */
  function renderDrawer() {
    var items = $('#cartPanelItems'); if (!items) return;
    var cart = loadCart(), cat = loadCatalog();
    var keys = Object.keys(cart);
    var footer = $('#cartPanelFooter');
    if (!keys.length) {
      items.innerHTML = '<div class="cart-empty"><i class="fa fa-shopping-cart"></i><p>Seu carrinho está vazio</p></div>';
      if (footer) footer.style.display = 'none';
      return;
    }
    var html = '<div class="cart-items-header"><span>Produto</span><span>Preço</span><span>Qtd</span><span>Total</span><span></span></div>';
    keys.forEach(function (k) {
      var p = cat[k]; if (!p) return;
      var it = cart[k];
      html += '<div class="cart-item-row">' +
        '<div class="cart-item-product">' +
        '<img src="' + esc(url(p.img)) + '" alt="' + esc(p.name) + '" loading="lazy" style="width:52px;height:52px;object-fit:cover;border-radius:8px">' +
        '<span class="cip-name">' + esc(p.name) + '</span>' +
        '</div>' +
        '<div class="cart-item-price">' + money(p.price) + '</div>' +
        '<div class="cart-item-qty">' +
        '<button class="ci-qty-btn" onclick="vsQty(\'' + safeId(k) + '\',-1)">−</button>' +
        '<span class="ci-qty-val">' + it.qty + '</span>' +
        '<button class="ci-qty-btn" onclick="vsQty(\'' + safeId(k) + '\',1)">+</button>' +
        '</div>' +
        '<div class="cart-item-subtotal">' + money(p.price * it.qty) + '</div>' +
        '<div class="cart-item-remove"><button class="ci-remove" onclick="vsRemoveItem(\'' + safeId(k) + '\')" title="Remover"><i class="fa fa-trash"></i></button></div>' +
        '</div>';
    });
    items.innerHTML = html;
    var sub = cartSubtotal(cart);
    var el;
    if ((el = $('#cpSubtotal'))) el.textContent = money(sub);
    if ((el = $('#cpTotal'))) el.textContent = money(sub);
    if (footer) footer.style.display = '';
  }

  function toggleCart(open) {
    var panel = $('#cartPanel'), overlay = $('#cartOverlay');
    if (!panel) return;
    panel.classList.toggle('open', open);
    if (overlay) overlay.classList.toggle('open', open);
    document.body.classList.toggle('cart-lock', open);
    if (open) renderDrawer();
  }

  function renderBadges() {
    var cart = loadCart(), n = cartCount(cart);
    $$('.cart-count').forEach(function (el) {
      el.textContent = n;
      el.style.display = n ? 'flex' : 'none';
    });
    var mbn = $('#mbnBadge');
    if (mbn) { mbn.textContent = n; mbn.style.display = n ? 'flex' : 'none'; }
  }

  function renderAll() { renderBadges(); renderDrawer(); renderCartPage(); }

  /* ---------------- CHECKOUT WHATSAPP ---------------- */
  // Número do WhatsApp da loja: do servidor (configurável no painel admin)
  // com fallback para o valor fixo da config quando o servidor está offline.
  var waNumber = CFG.whatsapp; // padrão; atualizado pelo servidor ao carregar
  function loadWaNumber() {
    if (window.PodpahhDB && window.PodpahhDB.getSettings) {
      window.PodpahhDB.getSettings().then(function (s) {
        if (s && s.whatsapp) {
          var d = String(s.whatsapp).replace(/\D/g, '');
          // Banco novo guarda com 55; banco antigo sem 55: prefixa automaticamente
          if (d && !d.startsWith('55')) d = '55' + d;
          if (d) waNumber = d;
        }
      }).catch(function () { /* mantém padrão */ });
    }
  }

  function loggedUser() {
    try {
      var s = JSON.parse(localStorage.getItem('podpahh_session_v1'));
      if (s && s.user) return s.user;
    } catch (e) {}
    try { return JSON.parse(localStorage.getItem('podpahh_logged_user')); } catch (e) { return null; }
  }

  function getSessionToken() {
    try {
      var s = JSON.parse(localStorage.getItem('podpahh_session_v1'));
      if (s && s.token) return s.token;
    } catch (e) {}
    return null;
  }

  var cachedAddresses = [];
  var selectedAddressId = null;

  async function loadCartAddresses() {
    var user = loggedUser();
    var token = getSessionToken();
    if (!user || !token || !window.PodpahhDB || !window.PodpahhDB.getAddresses) {
      cachedAddresses = [];
      selectedAddressId = null;
      renderCartAddressSection();
      return;
    }
    try {
      var res = await window.PodpahhDB.getAddresses(token);
      if (res && res.success) {
        cachedAddresses = res.data || [];
        var def = cachedAddresses.find(function(a) { return a.is_default; }) || cachedAddresses[0];
        if (!selectedAddressId && def) {
          selectedAddressId = def.id;
        } else if (selectedAddressId && !cachedAddresses.some(function(a) { return a.id === selectedAddressId; })) {
          selectedAddressId = def ? def.id : null;
        }
      } else {
        cachedAddresses = [];
        selectedAddressId = null;
      }
    } catch (e) {
      cachedAddresses = [];
      selectedAddressId = null;
    }
    renderCartAddressSection();
  }

  window.vsSelectAddress = function(id) {
    selectedAddressId = id;
    renderCartAddressSection();
  };

  window.vsToggleAddressForm = function(show) {
    var formEl = $('#cartAddressFormWrap');
    if (formEl) formEl.style.display = show ? 'block' : 'none';
  };

  window.vsSaveAddressFromCart = async function(e) {
    if (e) e.preventDefault();
    var form = $('#cartAddressForm');
    if (!form) return;
    var token = getSessionToken();
    if (!token) {
      alert('Faça login para salvar o endereço.');
      window.location.href = base() + '/pages/minha-conta.html';
      return;
    }
    var data = {
      label: form.label ? form.label.value.trim() : 'Casa',
      recipient_name: form.recipient_name ? form.recipient_name.value.trim() : '',
      phone: form.phone ? form.phone.value.trim() : '',
      postal_code: form.postal_code ? form.postal_code.value.trim() : '',
      street: form.street ? form.street.value.trim() : '',
      number: form.number ? form.number.value.trim() : '',
      complement: form.complement ? form.complement.value.trim() : '',
      neighborhood: form.neighborhood ? form.neighborhood.value.trim() : '',
      city: form.city ? form.city.value.trim() : '',
      state: form.state ? form.state.value.trim() : '',
      is_default: true
    };
    if (!data.recipient_name || !data.phone || !data.postal_code || !data.street || !data.number || !data.neighborhood || !data.city || !data.state) {
      alert('Por favor, preencha todos os campos obrigatórios do endereço.');
      return;
    }
    try {
      var res = await window.PodpahhDB.saveAddress(data, token);
      if (!res || !res.success) {
        alert(res && res.error ? res.error : 'Erro ao salvar endereço.');
        return;
      }
      selectedAddressId = res.data.id;
      form.reset();
      window.vsToggleAddressForm(false);
      await loadCartAddresses();
    } catch (err) {
      alert('Erro de conexão ao salvar endereço.');
    }
  };

  function getSelectedAddress() {
    if (!selectedAddressId || !cachedAddresses.length) return null;
    return cachedAddresses.find(function(a) { return a.id === selectedAddressId; }) || cachedAddresses[0];
  }

  function renderCartAddressSection() {
    var mount = $('#cartAddressMount');
    if (!mount) return;
    var user = loggedUser();
    if (!user) {
      mount.innerHTML = '<div style="background:var(--bg3);border:1px solid var(--brd);padding:14px;border-radius:8px;margin-bottom:16px;text-align:center">' +
        '<p style="font-size:.85rem;margin:0 0 10px;color:var(--txt)">Identifique-se para carregar seus endereços salvos.</p>' +
        '<a href="../pages/minha-conta.html" class="pp-btn-ghost" style="display:inline-block"><i class="fa fa-user"></i> ENTRAR / CRIAR CONTA</a>' +
        '</div>';
      return;
    }

    var html = '<div style="background:var(--bg3);border:1px solid var(--brd);padding:14px;border-radius:8px;margin-bottom:16px">' +
      '<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px">' +
      '<span style="font-family:\'Barlow Condensed\',sans-serif;font-size:.82rem;font-weight:700;letter-spacing:2px;color:var(--c)"><i class="fa fa-map-marker-alt"></i> ENDEREÇO DE ENTREGA</span>' +
      (cachedAddresses.length ? '<button type="button" onclick="vsToggleAddressForm(true)" style="background:none;border:none;color:var(--c);font-size:.75rem;cursor:pointer">+ Novo Endereço</button>' : '') +
      '</div>';

    if (!cachedAddresses.length) {
      html += '<p style="font-size:.84rem;color:var(--dim);margin:0 0 12px">Nenhum endereço cadastrado. Cadastre para finalizar o pedido:</p>' +
        '<form id="cartAddressForm" onsubmit="vsSaveAddressFromCart(event)">' +
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="recipient_name" placeholder="Nome do Destinatário *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="tel" name="phone" placeholder="WhatsApp (DDD+Tel) *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="postal_code" placeholder="CEP (8 dígitos) *" maxlength="8" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="label" placeholder="Rótulo (ex: Casa, Trabalho)" style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:3fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="street" placeholder="Rua / Avenida *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="number" placeholder="Número *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="complement" placeholder="Complemento (Apto, Bloco)" style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="neighborhood" placeholder="Bairro *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:2fr 1fr;gap:8px;margin-bottom:10px">' +
        '<input type="text" name="city" placeholder="Cidade *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="state" placeholder="UF *" maxlength="2" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<button type="submit" class="pp-btn-ghost" style="width:100%;border-color:var(--c);color:var(--c)"><i class="fa fa-save"></i> SALVAR E USAR ESTE ENDEREÇO</button>' +
        '</form>';
    } else {
      html += '<div style="display:flex;flex-direction:column;gap:8px;margin-bottom:10px">';
      cachedAddresses.forEach(function(addr) {
        var isSel = addr.id === selectedAddressId;
        html += '<label style="display:flex;align-items:flex-start;gap:10px;background:var(--bg2);border:1px solid ' + (isSel ? 'var(--c)' : 'var(--brd)') + ';padding:10px;border-radius:6px;cursor:pointer">' +
          '<input type="radio" name="cart_addr_radio" ' + (isSel ? 'checked' : '') + ' onclick="vsSelectAddress(\'' + addr.id + '\')" style="margin-top:3px">' +
          '<div style="font-size:.82rem;color:var(--txt);line-height:1.4">' +
          '<b>[' + esc(addr.label || 'Endereço') + ']</b> ' + esc(addr.street) + ', ' + esc(addr.number) + (addr.complement ? ' (' + esc(addr.complement) + ')' : '') + '<br>' +
          esc(addr.neighborhood) + ' — ' + esc(addr.city) + '/' + esc(addr.state) + ' (CEP: ' + esc(addr.postal_code) + ')' +
          (addr.is_default ? ' <span style="color:var(--c);font-weight:700;font-size:.72rem">★ Padrão</span>' : '') +
          '</div></label>';
      });
      html += '</div>';

      html += '<div id="cartAddressFormWrap" style="display:none;margin-top:10px;border-top:1px dashed var(--brd);padding-top:10px">' +
        '<p style="font-size:.82rem;color:var(--dim);margin:0 0 8px">Adicionar novo endereço:</p>' +
        '<form id="cartAddressForm" onsubmit="vsSaveAddressFromCart(event)">' +
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="recipient_name" placeholder="Nome do Destinatário *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="tel" name="phone" placeholder="WhatsApp (DDD+Tel) *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="postal_code" placeholder="CEP (8 dígitos) *" maxlength="8" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="label" placeholder="Rótulo (ex: Casa, Trabalho)" style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:3fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="street" placeholder="Rua / Avenida *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="number" placeholder="Número *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:8px">' +
        '<input type="text" name="complement" placeholder="Complemento (Apto, Bloco)" style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="neighborhood" placeholder="Bairro *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:grid;grid-template-columns:2fr 1fr;gap:8px;margin-bottom:10px">' +
        '<input type="text" name="city" placeholder="Cidade *" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '<input type="text" name="state" placeholder="UF *" maxlength="2" required style="background:var(--bg2);border:1px solid var(--brd);color:var(--txt);padding:8px;font-size:.82rem">' +
        '</div>' +
        '<div style="display:flex;gap:8px">' +
        '<button type="submit" class="pp-btn-ghost" style="flex:1;border-color:var(--c);color:var(--c)"><i class="fa fa-save"></i> SALVAR</button>' +
        '<button type="button" onclick="vsToggleAddressForm(false)" class="pp-btn-ghost" style="border-color:rgba(255,50,50,.3);color:#ff5252">CANCELAR</button>' +
        '</div>' +
        '</form>' +
        '</div>';
    }

    html += '<div style="margin-top:10px;text-align:right"><a href="../pages/minha-conta.html" style="font-size:.75rem;color:var(--dim);text-decoration:underline">Gerenciar endereços na conta</a></div>';
    html += '</div>';
    mount.innerHTML = html;
  }

  function buildOrderMessage() {
    var cart = loadCart(), cat = loadCatalog();
    var user = loggedUser();
    var addr = getSelectedAddress();
    var lines = [];
    lines.push('*NOVO PEDIDO — PODPAHH* 🛒');
    lines.push('—————————————');
    var sub = 0, totalItems = 0;
    Object.keys(cart).forEach(function (k) {
      var p = cat[k]; if (!p) return;
      var tot = p.price * cart[k].qty;
      sub += tot; totalItems += cart[k].qty;
      lines.push('▪ *' + p.name + '*');
      lines.push('   ' + cart[k].qty + 'x ' + money(p.price) + ' = *' + money(tot) + '*');
    });
    lines.push('—————————————');
    lines.push('📦 Total de itens: ' + totalItems);
    lines.push('Total: *' + money(sub) + '*');
    lines.push('—————————————');
    lines.push('*DADOS DO CLIENTE*');
    lines.push('👤 Nome: ' + ((user && user.name) || (addr && addr.recipient_name) || ''));
    lines.push('📱 WhatsApp: ' + ((user && user.phone) ? formatPhoneBR(user.phone) : (addr && addr.phone ? formatPhoneBR(addr.phone) : '')));
    lines.push((user && user.email) ? ('✉️ E-mail: ' + user.email) : '✉️ E-mail:');
    lines.push('');
    lines.push('🏠 Endereço de entrega:');
    if (addr) {
      lines.push('Destinatário: ' + addr.recipient_name);
      lines.push('Tel: ' + formatPhoneBR(addr.phone));
      lines.push('CEP: ' + addr.postal_code);
      lines.push('Endereço: ' + addr.street + ', ' + addr.number + (addr.complement ? ' (' + addr.complement + ')' : ''));
      lines.push('Bairro: ' + addr.neighborhood + ' — ' + addr.city + '/' + addr.state);
      if (addr.label) lines.push('Rótulo: ' + addr.label);
    } else {
      lines.push('— (Nenhum endereço selecionado)');
    }
    lines.push('');
    lines.push('💳 Forma de pagamento: (responder: PIX ou Cartão)');
    lines.push('');
    lines.push('Olá! Quero finalizar este pedido. Podem confirmar? ✅');
    return lines.join('\n');
  }

  // Formata (41) 99999-9999 para exibir na mensagem
  function formatPhoneBR(digits) {
    var d = String(digits || '').replace(/\D/g, '');
    if (d.length === 11) return '(' + d.substring(0, 2) + ') ' + d.substring(2, 7) + '-' + d.substring(7);
    if (d.length === 10) return '(' + d.substring(0, 2) + ') ' + d.substring(2, 6) + '-' + d.substring(6);
    return d;
  }

  function checkoutUrl() {
    // encodeURIComponent só do texto; número limpo, só dígitos
    return 'https://wa.me/' + waNumber + '?text=' + encodeURIComponent(buildOrderMessage());
  }

  window.vsCheckout = function () {
    var cart = loadCart();
    if (!Object.keys(cart).length) { alert('Seu carrinho está vazio.'); return; }
    var user = loggedUser();
    if (!user) {
      if (confirm('Para finalizar a compra, é necessário fazer login. Ir para a página Minha Conta?')) {
        window.location.href = base() + '/pages/minha-conta.html';
      }
      return;
    }
    var addr = getSelectedAddress();
    if (!addr) {
      alert('Por favor, selecione ou cadastre um endereço de entrega para prosseguir.');
      return;
    }
    var cat = loadCatalog();
    // Registra o pedido no banco de dados ANTES de abrir o WhatsApp
    if (window.PodpahhDB && window.PodpahhDB.saveOrder) {
      var items = Object.keys(cart).map(function (k) {
        var p = cat[k] || {};
        return { id: k, name: p.name || k, price: p.price || 0, qty: cart[k].qty };
      });
      var sub = 0;
      items.forEach(function (i) { sub += i.price * i.qty; });
      window.PodpahhDB.saveOrder({
        items: items,
        subtotal: sub,
        total: sub,
        customer_id: user.id,
        customer_name: user.name || addr.recipient_name,
        customer_phone: user.phone || addr.phone,
        address_id: addr.id,
        address: addr.street + ', ' + addr.number + (addr.complement ? ' ' + addr.complement : '') + ' - ' + addr.neighborhood + ', ' + addr.city + '/' + addr.state + ' (CEP: ' + addr.postal_code + ')',
        payment_method: 'PIX'
      }).catch(function (e) { console.warn('Falha ao registrar pedido no banco:', e); });
    }
    window.open(checkoutUrl(), '_blank');
  };
  window.vsClearCart = function () { saveCart({}); };

  /* ---------------- CART PAGE (pages/carrinho.html) ---------------- */
  function isCartPage() { return !!$('#podpahh-cart-page'); }
  function renderCartPage() {
    if (!isCartPage()) return;
    var mount = $('#podpahh-cart-page');
    var cart = loadCart(), cat = loadCatalog();
    var keys = Object.keys(cart);
    if (!keys.length) {
      mount.innerHTML = '<div class="pp-cart-empty"><i class="fa fa-shopping-bag"></i>' +
        '<h2>Seu carrinho está vazio</h2>' +
        '<p>Adicione produtos para continuar.</p>' +
        '<a class="pp-btn-primary" href="../index.html">VER PRODUTOS</a></div>';
      return;
    }
    var rows = '', sub = 0;
    keys.forEach(function (k) {
      var p = cat[k]; if (!p) return;
      var it = cart[k], tot = p.price * it.qty; sub += tot;
      rows += '<tr>' +
        '<td class="ppc-img"><img src="' + esc(url(p.img)) + '" alt=""></td>' +
        '<td class="ppc-name"><a href="' + url(p.url || '#') + '">' + esc(p.name) + '</a>' +
        '<div class="ppc-unit">' + money(p.price) + ' un.</div></td>' +
        '<td class="ppc-qty"><button onclick="vsQty(\'' + safeId(k) + '\',-1)">−</button>' +
        '<span>' + it.qty + '</span>' +
        '<button onclick="vsQty(\'' + safeId(k) + '\',1)">+</button></td>' +
        '<td class="ppc-total">' + money(tot) + '</td>' +
        '<td class="ppc-del"><button onclick="vsRemoveItem(\'' + safeId(k) + '\')" title="Remover"><i class="fa fa-trash"></i></button></td>' +
        '</tr>';
    });
    mount.innerHTML =
      '<h1 class="pp-cart-title"><i class="fa fa-shopping-bag"></i> MEU CARRINHO</h1>' +
      '<div class="pp-cart-grid">' +
      '<div class="pp-cart-items"><table class="pp-cart-table"><tbody>' + rows + '</tbody></table>' +
      '<div class="pp-cart-actions">' +
      '<a href="../pages/loja.html" class="pp-btn-ghost" style="display:none"></a>' +
      '<a href="../index.html" class="pp-btn-ghost"><i class="fa fa-arrow-left"></i> CONTINUAR COMPRANDO</a>' +
      '<button class="pp-btn-ghost" onclick="vsClearCart()"><i class="fa fa-trash"></i> ESVAZIAR</button>' +
      '</div></div>' +
      '<aside class="pp-cart-summary">' +
      '<h3>RESUMO DO PEDIDO</h3>' +
      '<div id="cartAddressMount"></div>' +
      '<div class="pps-row"><span>Subtotal</span><b>' + money(sub) + '</b></div>' +
      '<div class="pps-row pps-frete"><span>Frete</span><b>calculado no checkout</b></div>' +
      '<button class="pp-btn-checkout" onclick="vsCheckout()"><i class="fa-brands fa-whatsapp"></i> FINALIZAR NO WHATSAPP</button>' +
      '<p class="pps-note">Você será redirecionado ao WhatsApp para confirmar endereço e pagamento.</p>' +
      '</aside></div>';
  }

  /* ---------------- AGE GATE ---------------- */
  function ageGate() {
    var gate = $('#gate');
    if (!gate) return;
    var ok = false;
    try { ok = localStorage.getItem(CFG.ageKey) === '1'; } catch (e) {}
    if (!ok) {
      gate.style.display = 'flex';
      document.body.classList.add('gate-blocked');
    }
    window.vsAgeOk = function () {
      try { localStorage.setItem(CFG.ageKey, '1'); } catch (e) {}
      gate.style.display = 'none';
      document.body.classList.remove('gate-blocked');
    };
    window.vsAgeNo = window.vsAgeNo || function () {
      window.location.href = 'https://www.google.com';
    };
  }

  /* ---------------- SEARCH (estático: redireciona p/ loja) ---------------- */
  function wireSearch() {
    $$('form[role="search"]').forEach(function (f) {
      f.addEventListener('submit', function (e) {
        e.preventDefault();
        var inp = $('input[name="s"], input[type="search"], input', f);
        var q = inp ? inp.value.trim() : '';
        var base = (document.body.getAttribute('data-base') || '.');
        window.location.href = base + '/pages/loja.html' + (q ? '?q=' + encodeURIComponent(q) : '');
      });
    });
    // filtro client-side na loja
    var params = new URLSearchParams(location.search);
    var q = (params.get('q') || '').toLowerCase();
    if (q && $$('.pcard').length) {
      $$('.pcard').forEach(function (card) {
        var nameEl = $('.pcard-name', card);
        var name = nameEl ? nameEl.textContent.toLowerCase() : '';
        var li = card.closest('li') || card;
        if (name.indexOf(q) === -1) li.style.display = 'none';
      });
    }
  }

  /* ---------------- LAZY LOAD (data-src → src) ---------------- */
  function lazyImages() {
    var PH = (function () { try { return base() + '/assets/images/placeholder.svg'; } catch (e) { return ''; } })();
    var imgs = $$('.pcard img[data-src], img[data-src]');
    if (!('IntersectionObserver' in window)) {
      imgs.forEach(function (im) { im.src = url(im.getAttribute('data-src')); });
      return;
    }
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (!en.isIntersecting) return;
        var im = en.target;
        var ds = im.getAttribute('data-src');
        if (ds) {
          im.onerror = function () { im.onerror = null; if (PH) im.src = PH; };
          im.src = url(ds);
        }
        var dss = im.getAttribute('data-srcset');
        if (dss) im.setAttribute('srcset', dss);
        im.removeAttribute('data-src');
        io.unobserve(im);
      });
    }, { rootMargin: '300px' });
    imgs.forEach(function (im) { io.observe(im); });
  }

  /* ---------------- BROKEN IMAGE FALLBACK ---------------- */
  function fallbackBroken() {
    var PH = (function () { try { return base() + '/assets/images/placeholder.svg'; } catch (e) { return ''; } })();
    if (!PH) return;
    document.addEventListener('error', function (e) {
      if (e.target.tagName === 'IMG' && e.target.src && !e.target.src.endsWith('placeholder.svg')) {
        e.target.onerror = null;
        e.target.src = PH;
      }
    }, true);
  }

  /* ---------------- ADMIN PRODUCTS SYNC (server local / Supabase) ---------------- */
  function syncAdminProducts() {
    // Rota pública: só produtos com estoque, sem dados sensíveis de clientes/admin
    fetch('http://localhost:3000/api/public/products')
      .then(function (r) { return r.json(); })
      .then(function (json) {
        if (!json.success || !json.data || !json.data.length) return;
        var map = {};
        json.data.forEach(function (p) {
          var pid = p.source_id || p.id; // produtos importados mantêm o ID original do catálogo
          map[pid] = {
            name: p.name,
            price: p.price,
            img: p.image || '',
            url: p.url || '',
            category: p.category
          };
        });
        window.PODPAHH_ADMIN_PRODUCTS = map;
        renderAll(); // re-renderiza carrinho/badges com preços atualizados do banco
      })
      .catch(function () { /* servidor offline: segue com catálogo estático */ });
  }

  /* ---------------- INIT ---------------- */
  document.addEventListener('DOMContentLoaded', function () {
    scrapeCards();
    ageGate();
    wireSearch();
    lazyImages();
    fallbackBroken();
    renderAll();
    loadCartAddresses();
    renderWishCount();
    syncWishlistFromServer(); // mescla favoritos da conta no cache local
    syncAdminProducts();
    loadWaNumber(); // puxa o número do WhatsApp configurado no painel admin
    // fechar drawer com overlay ja tem onclick; garante ESC
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') toggleCart(false);
    });
  });
})();
