/* ================================================================
   PODPAHH — Store Engine (static)
   Carrinho localStorage + Age Gate + Wishlist + Checkout WhatsApp
   Sem dependências. Carregar em todas as páginas.
   ================================================================ */
(function () {
  'use strict';

  /* ---------------- CONFIG ---------------- */
  var CFG = {
    // WhatsApp de checkout (55 + DDD + número, só dígitos)
    whatsapp: '5547999453628',
    maxQty: 99,
    ageKey: 'podpahh_age_ok',
    cartKey: 'podpahh_cart_v1',
    catKey: 'podpahh_catalog_v2',
    wishKey: 'podpahh_wishlist_v1'
  };

  var $ = function (s, r) { return (r || document).querySelector(s); };
  var $$ = function (s, r) { return Array.prototype.slice.call((r || document).querySelectorAll(s)); };

  function money(v) {
    return 'R$ ' + v.toLocaleString('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  function parsePrice(txt) {
    // "R$ 1.234,56" -> 1234.56
    var m = (txt || '').replace(/[^\d,\.]/g, '');
    var parts = m.split(',');
    var intPart = parts.length > 1 ? parts[0] : m;
    intPart = intPart.replace(/\./g, '');
    var dec = parts.length > 1 ? parts[1] : '00';
    var v = parseFloat(intPart + '.' + dec.slice(0, 2));
    return isNaN(v) ? 0 : v;
  }
  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }
  function base() {
    return (document.body.getAttribute('data-base') || '.');
  }
  function safeId(s) {
    return String(s).replace(/[^A-Za-z0-9_-]/g, '');
  }
  function url(p) {
    if (!p) return p;
    if (/^(https?:|#|mailto:|data:)/.test(p)) return p;
    if (p.indexOf('assets/') === 0 || p.indexOf('produto/') === 0) return base() + '/' + p;
    return p;
  }

  /* ---------------- CATALOG (global file + scraped cards) ---------------- */
  function loadCatalog() {
    var cat = {};
    // 1) global catalog generated by cleanup script (authoritative)
    if (window.PODPAHH_CATALOG) {
      for (var k in window.PODPAHH_CATALOG) cat[k] = window.PODPAHH_CATALOG[k];
    }
    // 2) merge products managed by Admin Panel (server local / Supabase)
    if (window.PODPAHH_ADMIN_PRODUCTS) {
      for (var a in window.PODPAHH_ADMIN_PRODUCTS) cat[a] = window.PODPAHH_ADMIN_PRODUCTS[a];
    }
    // 3) merge persisted scrape
    try {
      var saved = JSON.parse(localStorage.getItem(CFG.catKey)) || {};
      for (var s in saved) if (!cat[s]) cat[s] = saved[s];
    } catch (e) {}
    return cat;
  }
  function saveCatalog(cat) {
    try { localStorage.setItem(CFG.catKey, JSON.stringify(cat)); } catch (e) {}
  }
  function scrapeCards() {
    var cat = loadCatalog();
    var changed = false;
    $$('.pcard').forEach(function (card) {
      var id = (card.id || '').replace('pcard-', '');
      if (!id || cat[id]) return; // global catalog wins
      var nameEl = $('.pcard-name', card);
      var priceEl = $('.pcard-price', card);
      var img = $('img', card);
      var link = $('a.pcard-img, a.pcard-name', card) || $('a', card);
      var brandEl = $('.pcard-brand', card);
      var rawImg = img ? (img.getAttribute('data-src') || img.getAttribute('src') || '') : '';
      try {
        // caminho absoluto do site: a imagem do carrinho funciona em qualquer página
        if (rawImg && !/^(https?:|data:|blob:)/.test(rawImg)) rawImg = new URL(rawImg, document.baseURI).pathname;
      } catch (e) {}
      cat[id] = {
        name: nameEl ? nameEl.textContent.trim() : 'Produto',
        price: priceEl ? parsePrice(priceEl.textContent) : 0,
        img: rawImg,
        url: link ? link.getAttribute('href') : '',
        brand: brandEl ? brandEl.textContent.trim() : ''
      };
      changed = true;
    });
    if (changed) saveCatalog(cat);
    return cat;
  }

  /* ---------------- CART STATE ---------------- */
  function loadCart() {
    try { return JSON.parse(localStorage.getItem(CFG.cartKey)) || {}; }
    catch (e) { return {}; }
  }
  function saveCart(cart) {
    try { localStorage.setItem(CFG.cartKey, JSON.stringify(cart)); } catch (e) {}
    renderAll();
  }
  function cartCount(cart) {
    var n = 0; for (var k in cart) n += cart[k].qty; return n;
  }
  function cartSubtotal(cart) {
    var cat = loadCatalog(), s = 0;
    for (var k in cart) {
      var p = cat[k]; if (p) s += p.price * cart[k].qty;
    }
    return s;
  }

  /* ---------------- PUBLIC API (onclick handlers no HTML) ---------------- */
  window.vsAddToCart = function (id, btn) {
    var cat = loadCatalog();
    var p = cat[id];
    if (!p) { // página sem o card? tenta achar em outro lugar
      cat = scrapeCards(); p = cat[id];
    }
    if (!p) return;
    var cart = loadCart();
    cart[id] = cart[id] || { qty: 0 };
    cart[id].qty = Math.min(cart[id].qty + 1, CFG.maxQty);
    saveCart(cart);
    if (btn) {
      var old = btn.innerHTML;
      btn.innerHTML = '<i class="fa fa-check"></i>ADICIONADO';
      btn.style.background = 'linear-gradient(135deg,#00c853,#00e676)';
      setTimeout(function () { btn.innerHTML = old; btn.style.background = ''; }, 1200);
    }
  };

  window.vsOpenCartStore = function () { toggleCart(true); };
  window.vsCloseCartStore = function () { toggleCart(false); };

  /* Os botões do site (header + menu inferior) chamam vsOpenCart/vsCloseCart,
     definidos originalmente no bundle legado (bdc5c89a...js) que não é mais
     carregado. Expõe aqui para o carrinho funcionar sem o bundle. */
  window.vsOpenCart = window.vsOpenCartStore;
  window.vsCloseCart = window.vsCloseCartStore;

  /* CSS do estado aberto: o painel usa style inline right:-440px,
     então a regra .open precisa de !important para vencer o inline. */
  if (!document.getElementById('podpahh-cart-css')) {
    var st = document.createElement('style');
    st.id = 'podpahh-cart-css';
    st.textContent =
      '#cartPanel.open{right:0 !important}' +
      '#cartOverlay.open{opacity:1 !important;pointer-events:auto !important}' +
      'body.cart-lock{overflow:hidden}';
    document.head.appendChild(st);
  }

  window.vsQty = function (id, delta) {
    var cart = loadCart();
    if (!cart[id]) return;
    cart[id].qty += delta;
    if (cart[id].qty <= 0) delete cart[id];
    saveCart(cart);
  };

  window.vsRemoveItem = function (id) {
    var cart = loadCart();
    delete cart[id];
    saveCart(cart);
  };

  window.vsToggleWish = function (id, btn) {
    var wish = loadWish();
    if (wish[id]) { delete wish[id]; if (btn) btn.classList.remove('on'); }
    else { wish[id] = 1; if (btn) btn.classList.add('on'); }
    try { localStorage.setItem(CFG.wishKey, JSON.stringify(wish)); } catch (e) {}
    renderWishCount();
  };

  /* ---------------- WISHLIST ---------------- */
  function loadWish() {
    try { return JSON.parse(localStorage.getItem(CFG.wishKey)) || {}; }
    catch (e) { return {}; }
  }
  function renderWishCount() {
    var n = Object.keys(loadWish()).length;
    $$('.wish-count').forEach(function (el) {
      el.textContent = n;
      el.style.display = n ? '' : 'none';
    });
  }
  // Marca de vermelho os corações já favoritados (após reload)
  function syncWishButtons() {
    var wish;
    try { wish = JSON.parse(localStorage.getItem(CFG.wishKey)) || {}; }
    catch (e) { wish = {}; }
    $$('.pcard-wish[onclick]').forEach(function (btn) {
      var m = (btn.getAttribute('onclick') || '').match(/vsToggleWish\((\d+)/);
      if (m && wish[m[1]]) btn.classList.add('on');
    });
  }

  /* ---------------- DRAWER RENDER ---------------- */
  function renderDrawer() {
    var items = $('#cartPanelItems'); if (!items) return;
    var cart = loadCart(), cat = loadCatalog();
    var keys = Object.keys(cart);
    var footer = $('#cartPanelFooter');
    if (!keys.length) {
      items.innerHTML = '<div class="cart-empty"><i class="fa fa-shopping-cart"></i><p>Seu carrinho está vazio</p></div>';
      if (footer) footer.style.display = 'none';
      return;
    }
    var html = '<div class="cart-items-header"><span>Produto</span><span>Preço</span><span>Qtd</span><span>Total</span><span></span></div>';
    keys.forEach(function (k) {
      var p = cat[k]; if (!p) return;
      var it = cart[k];
      html += '<div class="cart-item-row">' +
        '<div class="cart-item-product">' +
        '<img src="' + esc(url(p.img)) + '" alt="' + esc(p.name) + '" loading="lazy" style="width:52px;height:52px;object-fit:cover;border-radius:8px">' +
        '<span class="cip-name">' + esc(p.name) + '</span>' +
        '</div>' +
        '<div class="cart-item-price">' + money(p.price) + '</div>' +
        '<div class="cart-item-qty">' +
        '<button class="ci-qty-btn" onclick="vsQty(\'' + safeId(k) + '\',-1)">−</button>' +
        '<span class="ci-qty-val">' + it.qty + '</span>' +
        '<button class="ci-qty-btn" onclick="vsQty(\'' + safeId(k) + '\',1)">+</button>' +
        '</div>' +
        '<div class="cart-item-subtotal">' + money(p.price * it.qty) + '</div>' +
        '<div class="cart-item-remove"><button class="ci-remove" onclick="vsRemoveItem(\'' + safeId(k) + '\')" title="Remover"><i class="fa fa-trash"></i></button></div>' +
        '</div>';
    });
    items.innerHTML = html;
    var sub = cartSubtotal(cart);
    var el;
    if ((el = $('#cpSubtotal'))) el.textContent = money(sub);
    if ((el = $('#cpTotal'))) el.textContent = money(sub);
    if (footer) footer.style.display = '';
  }

  function toggleCart(open) {
    var panel = $('#cartPanel'), overlay = $('#cartOverlay');
    if (!panel) return;
    panel.classList.toggle('open', open);
    if (overlay) overlay.classList.toggle('open', open);
    document.body.classList.toggle('cart-lock', open);
    if (open) renderDrawer();
  }

  function renderBadges() {
    var cart = loadCart(), n = cartCount(cart);
    $$('.cart-count').forEach(function (el) {
      el.textContent = n;
      el.style.display = n ? 'flex' : 'none';
    });
    var mbn = $('#mbnBadge');
    if (mbn) { mbn.textContent = n; mbn.style.display = n ? 'flex' : 'none'; }
  }

  function renderAll() { renderBadges(); renderDrawer(); renderCartPage(); renderWishlistPage(); }

  /* ---------------- CHECKOUT WHATSAPP ---------------- */
  // Número do WhatsApp da loja: do servidor (configurável no painel admin)
  // com fallback para o valor fixo da config quando o servidor está offline.
  var waNumber = CFG.whatsapp; // padrão; atualizado pelo servidor ao carregar
  function loadWaNumber() {
    if (window.PodpahhDB && window.PodpahhDB.getSettings) {
      window.PodpahhDB.getSettings().then(function (s) {
        if (s && s.whatsapp) {
          var d = String(s.whatsapp).replace(/\D/g, '');
          // Banco novo guarda com 55; banco antigo sem 55: prefixa automaticamente
          if (d && !d.startsWith('55')) d = '55' + d;
          if (d) waNumber = d;
        }
      }).catch(function () { /* mantém padrão */ });
    }
  }

  function loggedUser() {
    try { return JSON.parse(localStorage.getItem('podpahh_logged_user')); } catch (e) { return null; }
  }

  function getSessionToken() {
    try {
      var s = JSON.parse(localStorage.getItem('podpahh_session_v1'));
      if (s && s.token) return s.token;
    } catch (e) {}
    return null;
  }

  // WhatsApp válido: 10 ou 11 dígitos, DDD 11-99 (11 dígitos = celular com 9)
  function validCustomerPhone(v) {
    var d = String(v || '').replace(/\D/g, '');
    if (d.length !== 10 && d.length !== 11) return '';
    var ddd = parseInt(d.substring(0, 2), 10);
    if (ddd < 11 || ddd > 99) return '';
    if (d.length === 11 && d[2] !== '9') return '';
    return d;
  }

  function loginRedirect(msg) {
    if (msg) alert(msg);
    window.location.href = base() + '/pages/minha-conta.html';
  }

  function buildOrderMessage() {
    var cart = loadCart(), cat = loadCatalog();
    var user = loggedUser();
    var lines = [];
    lines.push('*NOVO PEDIDO — PODPAHH* 🛒');
    lines.push('—————————————');
    var sub = 0, totalItems = 0;
    Object.keys(cart).forEach(function (k) {
      var p = cat[k]; if (!p) return;
      var tot = p.price * cart[k].qty;
      sub += tot; totalItems += cart[k].qty;
      lines.push('▪ *' + p.name + '*');
      lines.push('   ' + cart[k].qty + 'x ' + money(p.price) + ' = *' + money(tot) + '*');
    });
    lines.push('—————————————');
    lines.push('📦 Total de itens: ' + totalItems);
    lines.push('Total: *' + money(sub) + '*');
    lines.push('—————————————');
    // Dados do cliente VÊM do cadastro — preenchidos automaticamente, sem perguntar de novo
    lines.push('*DADOS DO CLIENTE (cadastro)*');
    lines.push('👤 Nome: ' + ((user && user.name) || '—'));
    lines.push('📱 WhatsApp: ' + ((user && user.phone) ? formatPhoneBR(user.phone) : '—'));
    lines.push((user && user.email) ? ('✉️ E-mail: ' + user.email) : '✉️ E-mail: —');
    lines.push('');
    lines.push('🏠 Endereço de entrega:');
    if (window.__podpahh_selected_address_text) {
      lines.push(window.__podpahh_selected_address_text.split('\n').map(l => l ? '   ' + l : l).join('\n'));
    } else {
      lines.push('   [endereço não selecionado — pedido bloqueado]');
    }
    lines.push('💳 Forma de pagamento: (responder: PIX ou Cartão)');
    lines.push('');
    lines.push('Olá! Quero finalizar este pedido. Podem confirmar? ✅');
    return lines.join('\n');
  }

  // Formata (41) 99999-9999 para exibir na mensagem
  function formatPhoneBR(digits) {
    var d = String(digits || '').replace(/\D/g, '');
    if (d.length === 11) return '(' + d.substring(0, 2) + ') ' + d.substring(2, 7) + '-' + d.substring(7);
    if (d.length === 10) return '(' + d.substring(0, 2) + ') ' + d.substring(2, 6) + '-' + d.substring(6);
    return d;
  }

  function checkoutUrl() {
    // encodeURIComponent só do texto; número limpo, só dígitos
    return 'https://wa.me/' + waNumber + '?text=' + encodeURIComponent(buildOrderMessage());
  }

  // ===== FLUXO DE CHECKOUT COM ENDEREÇO OBRIGATÓRIO =====
  // 1. Carrinho vazio → alerta. 2. Não logado → Minha Conta.
  // 3. Busca endereços do cliente no servidor (rota protegida por token).
  //    - Tem endereços → modal lista + "CONFIRMAR E FINALIZAR".
  //    - Sem endereços → abre direto o formulário de novo endereço.
  // 4. Ao confirmar: registra o pedido com address_id + texto do endereço
  //    e abre o WhatsApp com o resumo completo.

  function formatAddressText(a) {
    if (!a) return '';
    var l = [];
    l.push('   ' + (a.street || '') + ', ' + (a.number || '') + (a.complement ? ' - ' + a.complement : ''));
    l.push('   ' + (a.neighborhood || '') + ' — ' + (a.city || '') + '/' + (a.state || ''));
    l.push('   CEP ' + String(a.postal_code || '').replace(/^(\d{5})(\d{3})$/, '$1-$2'));
    if (a.recipient_name) l.push('   Receber: ' + a.recipient_name + (a.phone ? ' (' + formatPhoneBR(a.phone) + ')' : ''));
    return l.filter(Boolean).join('\n');
  }

  // Extrai dígitos de qualquer string
  function onlyDigits(s) { return String(s || '').replace(/\D/g, ''); }

  // Máscara CEP: 12345-678
  function maskCep(v) {
    var d = onlyDigits(v).substring(0, 8);
    return d.length > 5 ? d.substring(0, 5) + '-' + d.substring(5) : d;
  }

  // Máscara telefone BR: (41) 99999-9999
  function maskPhoneBR(v) {
    var d = onlyDigits(v).substring(0, 11);
    if (d.length <= 2) return d;
    if (d.length <= 6) return '(' + d.substring(0, 2) + ') ' + d.substring(2);
    if (d.length <= 10) return '(' + d.substring(0, 2) + ') ' + d.substring(2, 6) + '-' + d.substring(6);
    return '(' + d.substring(0, 2) + ') ' + d.substring(2, 7) + '-' + d.substring(7);
  }

  // Preenche cidade/estado automaticamente via ViaCEP
  function viacepLookup(cepDigits) {
    return fetch('https://viacep.com.br/ws/' + cepDigits + '/json/')
      .then(function (r) { return r.json(); })
      .catch(function () { return null; });
  }

  // Fecha o modal de endereço (remove overlay do DOM)
  function closeAddressModal() {
    var ov = document.getElementById('pp-addr-overlay');
    if (ov) ov.remove();
  }

  // Monta o <option>-less form HTML do modal (campos do schema do servidor)
  function addressFormFieldsHTML(pre) {
    pre = pre || {};
    var user = loggedUser() || {};
    return '' +
      '<div class="pp-form-grid">' +
      '<div class="pp-form-field"><label>CEP *</label>' +
      '<input id="pp-cep" inputmode="numeric" maxlength="9" value="' + esc(pre.postal_code || '') + '" placeholder="00000-000"></div>' +
      '<div class="pp-form-field"><label>Rua / Avenida *</label>' +
      '<input id="pp-street" maxlength="160" value="' + esc(pre.street || '') + '" placeholder="Nome da rua"></div>' +
      '<div class="pp-form-field pp-f-narrow"><label>Número *</label>' +
      '<input id="pp-number" maxlength="20" value="' + esc(pre.number || '') + '" placeholder="123"></div>' +
      '<div class="pp-form-field pp-f-narrow"><label>Complemento</label>' +
      '<input id="pp-complement" maxlength="80" value="' + esc(pre.complement || '') + '" placeholder="Apto, bloco... (opcional)"></div>' +
      '<div class="pp-form-field"><label>Bairro *</label>' +
      '<input id="pp-neighborhood" maxlength="120" value="' + esc(pre.neighborhood || '') + '" placeholder="Bairro"></div>' +
      '<div class="pp-form-field"><label>Cidade *</label>' +
      '<input id="pp-city" maxlength="100" value="' + esc(pre.city || '') + '" placeholder="Cidade"></div>' +
      '<div class="pp-form-field pp-f-narrow"><label>UF *</label>' +
      '<input id="pp-state" maxlength="2" style="text-transform:uppercase" value="' + esc(pre.state || '') + '" placeholder="SC"></div>' +
      '<div class="pp-form-field"><label>Quem vai receber *</label>' +
      '<input id="pp-recipient" maxlength="100" value="' + esc(pre.recipient_name || user.name || '') + '" placeholder="Nome completo"></div>' +
      '<div class="pp-form-field"><label>Telefone de contato *</label>' +
      '<input id="pp-addr-phone" inputmode="numeric" maxlength="15" value="' + esc(pre.phone || (user.phone ? maskPhoneBR(user.phone) : '')) + '" placeholder="(41) 99999-9999"></div>' +
      '<div class="pp-form-field pp-f-full"><label>Identificador (ex.: Casa, Trabalho)</label>' +
      '<input id="pp-label" maxlength="80" value="' + esc(pre.label || '') + '" placeholder="Casa (opcional)"></div>' +
      '</div>';
  }

  // Faz a validação client-side (o servidor revalida tudo)
  function readAddressFormValues() {
    var g = function (id) { var el = document.getElementById(id); return el ? el.value.trim() : ''; };
    return {
      postal_code: onlyDigits(g('pp-cep')),
      street: g('pp-street'),
      number: g('pp-number'),
      complement: g('pp-complement'),
      neighborhood: g('pp-neighborhood'),
      city: g('pp-city'),
      state: g('pp-state').toUpperCase(),
      recipient_name: g('pp-recipient'),
      phone: onlyDigits(g('pp-addr-phone')),
      label: g('pp-label')
    };
  }

  function validateAddressForm(v) {
    if (v.postal_code.length !== 8) return 'Informe o CEP completo (8 dígitos).';
    if (!v.street) return 'Informe a rua.';
    if (!v.number) return 'Informe o número.';
    if (!v.neighborhood) return 'Informe o bairro.';
    if (!v.city) return 'Informe a cidade.';
    if (!/^[A-Z]{2}$/.test(v.state)) return 'Informe a UF (2 letras).';
    if (!v.recipient_name) return 'Informe quem vai receber.';
    if (!validCustomerPhone(v.phone)) return 'Informe um telefone válido com DDD (ex: (41) 99999-9999).';
    return null;
  }

  // Bind das máscaras + ViaCEP nos inputs do formulário
  function bindAddressFormEvents(onCepFilled) {
    var cep = document.getElementById('pp-cep');
    var phone = document.getElementById('pp-addr-phone');
    if (cep) {
      cep.addEventListener('input', function () { this.value = maskCep(this.value); });
      cep.addEventListener('blur', function () {
        var d = onlyDigits(this.value);
        if (d.length !== 8) return;
        var st = document.getElementById('pp-street');
        if (st && st.value) return; // já preenchido manualmente
        viacepLookup(d).then(function (j) {
          if (!j || j.erro) return;
          var set = function (id, val) { var el = document.getElementById(id); if (el && !el.value) el.value = val || ''; };
          set('pp-street', j.logradouro);
          set('pp-neighborhood', j.bairro);
          set('pp-city', j.localidade);
          set('pp-state', j.uf);
          if (onCepFilled) onCepFilled();
        });
      });
    }
    if (phone) {
      phone.addEventListener('input', function () { this.value = maskPhoneBR(this.value); });
    }
  }

  // Envia o endereço ao servidor. Retorna Promise<addr|null>.
  // Exige sessão válida (token): sem token, manda para o login.
  function submitAddressToServer(v) {
    var token = getSessionToken();
    if (!token) {
      loginRedirect('Sua sessão expirou. Entre novamente para salvar o endereço.');
      return Promise.resolve(null);
    }
    return window.PodpahhDB.saveAddress({
      label: v.label || 'Casa',
      recipient_name: v.recipient_name,
      phone: v.phone,
      postal_code: v.postal_code,
      street: v.street,
      number: v.number,
      complement: v.complement,
      neighborhood: v.neighborhood,
      city: v.city,
      state: v.state,
      is_default: false
    }, token).then(function (r) {
      if (!r.success) {
        if (/sessão|expirad|autorizado/i.test(r.error || '')) {
          alert('Sua sessão expirou. Entre novamente na sua conta.');
          try { window.location.href = base() + '/pages/minha-conta.html'; } catch (e) {}
        } else {
          alert(r.error || 'Falha ao salvar o endereço.');
        }
        return null;
      }
      return r.data;
    }).catch(function (e) {
      console.warn('Erro ao criar endereço:', e);
      alert('Não foi possível salvar o endereço (servidor offline?).');
      return null;
    });
  }

  // Modal completo: lista de endereços salvos + botão adicionar novo
  function openAddressPicker(addresses, onConfirm) {
    closeAddressModal();
    var ov = document.createElement('div');
    ov.id = 'pp-addr-overlay';
    ov.className = 'pp-modal-overlay';
    var listHTML = (addresses || []).map(function (a, i) {
      return '<label class="pp-addr-item">' +
        '<input type="radio" name="pp-addr-choice" value="' + i + '"' + (i === 0 ? ' checked' : '') + '>' +
        '<div class="pp-addr-info">' +
        '<b>' + esc(a.label || 'Endereço ' + (i + 1)) + (a.is_default ? ' <span class="pp-addr-badge">PADRÃO</span>' : '') + '</b>' +
        '<span>' + esc(a.street + ', ' + a.number + (a.complement ? ' - ' + a.complement : '')) + '</span>' +
        '<span>' + esc(a.neighborhood + ' — ' + a.city + '/' + a.state) + '</span>' +
        '<span>CEP ' + esc(String(a.postal_code || '').replace(/^(\d{5})(\d{3})$/, '$1-$2')) + '</span>' +
        '</div></label>';
    }).join('');
    ov.innerHTML =
      '<div class="pp-modal">' +
      '<h3><i class="fa fa-map-marker-alt"></i> ONDE ENTREGAR?</h3>' +
      '<p class="pp-modal-sub">Escolha um endereço de entrega para finalizar o pedido.</p>' +
      '<div class="pp-addr-list">' + listHTML + '</div>' +
      '<div class="pp-modal-btns">' +
      '<button class="pp-btn-primary" id="pp-addr-confirm"><i class="fa fa-check"></i> CONFIRMAR E FINALIZAR</button>' +
      '<button class="pp-btn-ghost" id="pp-addr-new"><i class="fa fa-plus"></i> ADICIONAR NOVO ENDEREÇO</button>' +
      '<button class="pp-btn-ghost" id="pp-addr-cancel" style="color:#ff5252;border-color:rgba(255,50,50,.3)">CANCELAR</button>' +
      '</div></div>';
    document.body.appendChild(ov);
    document.getElementById('pp-addr-confirm').onclick = function () {
      var sel = ov.querySelector('input[name="pp-addr-choice"]:checked');
      var idx = sel ? parseInt(sel.value, 10) : 0;
      var addr = (addresses || [])[idx];
      if (!addr) { openAddressForm(null, addresses, onConfirm); return; }
      onConfirm(addr);
    };
    document.getElementById('pp-addr-new').onclick = function () { openAddressForm(null, addresses, onConfirm); };
    document.getElementById('pp-addr-cancel').onclick = closeAddressModal;
    ov.addEventListener('click', function (e) { if (e.target === ov) closeAddressModal(); });
  }

  // Modal do formulário de novo endereço (com máscaras e ViaCEP)
  function openAddressForm(pre, knownAddresses, onSaved) {
    closeAddressModal();
    var ov = document.createElement('div');
    ov.id = 'pp-addr-overlay';
    ov.className = 'pp-modal-overlay';
    ov.innerHTML =
      '<div class="pp-modal">' +
      '<h3><i class="fa fa-plus"></i> NOVO ENDEREÇO</h3>' +
      '<p class="pp-modal-sub">Preencha os dados de entrega. O CEP preenche rua, bairro e cidade automaticamente.</p>' +
      '<div id="pp-form-mount">' + addressFormFieldsHTML(pre) + '</div>' +
      '<div class="pp-modal-btns">' +
      '<button class="pp-btn-primary" id="pp-addr-save"><i class="fa fa-check"></i> SALVAR ENDEREÇO</button>' +
      (knownAddresses && knownAddresses.length ? '<button class="pp-btn-ghost" id="pp-addr-back"><i class="fa fa-arrow-left"></i> VOLTAR</button>' : '') +
      '<button class="pp-btn-ghost" id="pp-addr-cancel2" style="color:#ff5252;border-color:rgba(255,50,50,.3)">CANCELAR</button>' +
      '</div></div>';
    document.body.appendChild(ov);
    bindAddressFormEvents();
    document.getElementById('pp-addr-save').onclick = function () {
      var v = readAddressFormValues();
      var err = validateAddressForm(v);
      if (err) { alert(err); return; }
      this.disabled = true;
      var self = this;
      submitAddressToServer(v).then(function (saved) {
        self.disabled = false;
        if (!saved) return;
        onSaved(saved);
      });
    };
    var back = document.getElementById('pp-addr-back');
    if (back) back.onclick = function () {
      // volta para a lista (endereços podem ter mudado? não: só cria; lista atual é válida)
      openAddressPicker(knownAddresses, onSaved);
    };
    document.getElementById('pp-addr-cancel2').onclick = closeAddressModal;
    ov.addEventListener('click', function (e) { if (e.target === ov) closeAddressModal(); });
  }

  // Prossegue após endereço confirmado: salva pedido + abre WhatsApp.
  // Endereço é OBRIGATÓRIO: sem addr, nada acontece (sem fallback de chat).
  function proceedAfterAddress(addr) {
    closeAddressModal();
    if (!addr || !addr.id) {
      alert('Escolha ou cadastre um endereço de entrega para finalizar.');
      return;
    }
    var cart = loadCart(), cat = loadCatalog(), user = loggedUser();
    var addrText = formatAddressText(addr);
    window.__podpahh_selected_address_text = addrText;
    if (!window.PodpahhDB || !window.PodpahhDB.saveOrder) {
      alert('Servidor indisponível. Tente novamente em instantes.');
      return;
    }
    var items = Object.keys(cart).map(function (k) {
      var p = cat[k] || {};
      return { id: k, name: p.name || k, price: p.price || 0, qty: cart[k].qty };
    });
    var sub = 0;
    items.forEach(function (i) { sub += i.price * i.qty; });
    window.PodpahhDB.saveOrder({
      items: items,
      subtotal: sub,
      total: sub,
      customer_id: user && user.id,
      customer_name: user && user.name,
      customer_phone: user && user.phone,
      address_id: addr.id,
      address: addrText,
      payment_method: 'PIX'
    }).then(function (r) {
      if (!r || !r.success) {
        alert(r && r.error ? r.error : 'Pedido recusado: confira endereço e WhatsApp.');
        return;
      }
      window.open(checkoutUrl(), '_blank');
    }).catch(function () {
      alert('Falha de conexão ao registrar o pedido. Tente novamente.');
    });
  }

  window.vsCheckout = function () {
    var cart = loadCart();
    if (!Object.keys(cart).length) { alert('Seu carrinho está vazio.'); return; }
    var user = loggedUser();
    // Nome e WhatsApp VÁLIDO já vêm do cadastro — sem eles, volta pra conta.
    if (!user || !user.name || !validCustomerPhone(user.phone)) {
      loginRedirect('Para finalizar, entre na sua conta com nome e WhatsApp válidos.\n\nIr para Minha Conta?');
      return;
    }
    var token = getSessionToken();
    if (!token) {
      loginRedirect('Sua sessão expirou. Entre novamente para finalizar o pedido.');
      return;
    }
    // ENDEREÇO OBRIGATÓRIO: busca os endereços do cliente no servidor.
    if (!window.PodpahhDB || !window.PodpahhDB.getAddresses) {
      alert('Servidor indisponível. Tente novamente em instantes.');
      return;
    }
    window.PodpahhDB.getAddresses(token).then(function (r) {
      var addresses = (r && r.success && Array.isArray(r.data)) ? r.data : [];
      if (!r || !r.success) {
        alert((r && r.error) || 'Não foi possível carregar seus endereços. Tente novamente.');
        return;
      }
      if (!addresses.length) {
        // Cliente sem endereços: abre direto o formulário de cadastro
        openAddressForm(null, [], proceedAfterAddress);
      } else {
        openAddressPicker(addresses, proceedAfterAddress);
      }
    }).catch(function () {
      alert('Falha de conexão. Verifique a internet e tente novamente.');
    });
  };
  window.vsClearCart = function () { saveCart({}); };

  /* ---------------- CART PAGE (pages/carrinho.html) ---------------- */
  function isCartPage() { return !!$('#podpahh-cart-page'); }  function renderCartPage() {
    if (!isCartPage()) return;
    var mount = $('#podpahh-cart-page');
    var cart = loadCart(), cat = loadCatalog();
    var keys = Object.keys(cart);
    if (!keys.length) {
      mount.innerHTML = '<div class="pp-cart-empty"><i class="fa fa-shopping-bag"></i>' +
        '<h2>Seu carrinho está vazio</h2>' +
        '<p>Adicione produtos para continuar.</p>' +
        '<a class="pp-btn-primary" href="../index.html">VER PRODUTOS</a></div>';
      return;
    }
    var rows = '', sub = 0;
    keys.forEach(function (k) {
      var p = cat[k]; if (!p) return;
      var it = cart[k], tot = p.price * it.qty; sub += tot;
      rows += '<tr>' +
        '<td class="ppc-img"><img src="' + esc(url(p.img)) + '" alt=""></td>' +
        '<td class="ppc-name"><a href="' + url(p.url || '#') + '">' + esc(p.name) + '</a>' +
        '<div class="ppc-unit">' + money(p.price) + ' un.</div></td>' +
        '<td class="ppc-qty"><span>' + it.qty + ' un.</span></td>' +
        '<td class="ppc-total">' + money(tot) + '</td>' +
        '<td class="ppc-del"><button onclick="vsRemoveItem(\'' + safeId(k) + '\')" title="Remover"><i class="fa fa-trash"></i></button></td>' +
        '</tr>';
    });
    mount.innerHTML =
      '<h1 class="pp-cart-title"><i class="fa fa-shopping-bag"></i> MEU CARRINHO</h1>' +
      '<div class="pp-cart-grid">' +
      '<div class="pp-cart-items"><table class="pp-cart-table"><tbody>' + rows + '</tbody></table>' +
      '<div class="pp-cart-actions">' +
      '<a href="../pages/loja.html" class="pp-btn-ghost" style="display:none"></a>' +
      '<a href="../index.html" class="pp-btn-ghost"><i class="fa fa-arrow-left"></i> CONTINUAR COMPRANDO</a>' +
      '<button class="pp-btn-ghost" onclick="vsClearCart()"><i class="fa fa-trash"></i> ESVAZIAR</button>' +
      '</div></div>' +
      '<aside class="pp-cart-summary">' +
      '<h3>RESUMO DO PEDIDO</h3>' +
      '<div class="pps-row"><span>Subtotal</span><b>' + money(sub) + '</b></div>' +
      '<div class="pps-row pps-frete"><span>Frete</span><b>calculado no checkout</b></div>' +
      '<button class="pp-btn-checkout" onclick="vsCheckout()"><i class="fa-brands fa-whatsapp"></i> FINALIZAR NO WHATSAPP</button>' +
      '<p class="pps-note">Você será redirecionado ao WhatsApp para confirmar endereço e pagamento.</p>' +
      '</aside></div>';
  }

  /* ---------------- WISHLIST PAGE (pages/lista-de-desejos.html) ---------------- */
  // Remove da wishlist e re-renderiza a página (usado pelo botão X de cada card).
  window.vsRemoveWish = function (id, btn) {
    var wish = loadWish();
    if (!wish[id]) return;
    delete wish[id];
    try { localStorage.setItem(CFG.wishKey, JSON.stringify(wish)); } catch (e) {}
    if (btn) btn.closest('.wl-card')?.classList.add('wl-removing');
    renderWishCount();
    setTimeout(renderWishlistPage, 250);
  };

  function isWishlistPage() { return !!$('#podpahh-wishlist-page'); }
  function renderWishlistPage() {
    if (!isWishlistPage()) return;
    var mount = $('#podpahh-wishlist-page');
    var wish = loadWish(), cat = loadCatalog();
    var ids = Object.keys(wish);
    if (!ids.length) {
      mount.innerHTML = '<div class="pp-cart-empty"><i class="fa fa-heart"></i>' +
        '<h2>Sua lista de desejos está vazia</h2>' +
        '<p>Toque no coração dos produtos para salvá-los aqui.</p>' +
        '<a class="pp-btn-primary" href="../index.html">VER PRODUTOS</a></div>';
      return;
    }
    var cards = '';
    ids.forEach(function (k) {
      var p = cat[k];
      if (!p) return; // produto fora do catálogo: mantém salvo, não renderiza
      var baseId = String(k).indexOf('__') !== -1 ? String(k).split('__')[0] : k;
      cards +=
        '<div class="pcard wl-card" id="pcard-' + safeId(k) + '">' +
        '<a href="' + url(p.url || '#') + '" class="pcard-img">' +
        '<img src="' + esc(url(p.img)) + '" alt="' + esc(p.name) + '" loading="lazy">' +
        '</a>' +
        '<button class="pcard-remove-wish" onclick="vsRemoveWish(\'' + safeId(k) + '\',this)" title="Remover da lista"><i class="fa fa-times"></i></button>' +
        '<div class="pcard-body">' +
        (p.brand ? '<div class="pcard-brand">' + esc(p.brand) + '</div>' : '') +
        '<a href="' + url(p.url || '#') + '" class="pcard-name">' + esc(p.name) + '</a>' +
        '<div class="pcard-price-block">' +
        '<span class="pcard-price">' + money(p.price) + '</span>' +
        '</div>' +
        '<a class="pcard-add" style="text-decoration:none;justify-content:center" href="' + base() + '/pages/produto.html?id=' + encodeURIComponent(baseId) + '"><i class="fa fa-arrow-right"></i>VER MODELOS</a>' +
        '</div>' +
        '</div>';
    });
    if (!cards) {
      // todos os IDs salvos estão fora do catálogo atual
      mount.innerHTML = '<div class="pp-cart-empty"><i class="fa fa-heart-o"></i>' +
        '<h2>Nenhum produto encontrado</h2>' +
        '<p>Os produtos salvos não estão mais disponíveis no catálogo.</p>' +
        '<a class="pp-btn-primary" href="../index.html">VER PRODUTOS</a></div>';
      return;
    }
    mount.innerHTML =
      '<h1 class="pp-cart-title"><i class="fa fa-heart"></i> LISTA DE DESEJOS</h1>' +
      '<div class="wl-grid">' + cards + '</div>';
  }

  /* ---------------- AGE GATE ---------------- */
  function ageGate() {
    var gate = $('#gate');
    if (!gate) return;
    var ok = false;
    try { ok = localStorage.getItem(CFG.ageKey) === '1'; } catch (e) {}
    // ?gate=1 força exibir o gate novamente (para testar a tela de 18+)
    try {
      var params = new URLSearchParams(window.location.search);
      if (params.get('gate') === '1' || params.has('ver-idade')) {
        try { localStorage.removeItem(CFG.ageKey); } catch (e2) {}
        ok = false;
      }
    } catch (e3) {}
    if (!ok) {
      gate.style.display = 'flex';
      document.body.classList.add('gate-blocked');
    }
    window.vsAgeOk = function () {
      try { localStorage.setItem(CFG.ageKey, '1'); } catch (e) {}
      gate.style.display = 'none';
      document.body.classList.remove('gate-blocked');
    };
    window.vsAgeNo = window.vsAgeNo || function () {
      window.location.href = 'https://www.google.com';
    };
  }

  /* ---------------- SEARCH (estático: redireciona p/ loja) ---------------- */
  function wireSearch() {
    $$('form[role="search"]').forEach(function (f) {
      f.addEventListener('submit', function (e) {
        e.preventDefault();
        var inp = $('input[name="s"], input[type="search"], input', f);
        var q = inp ? inp.value.trim() : '';
        var base = (document.body.getAttribute('data-base') || '.');
        window.location.href = base + '/pages/loja.html' + (q ? '?q=' + encodeURIComponent(q) : '');
      });
    });
    // filtro client-side na loja
    var params = new URLSearchParams(location.search);
    var q = (params.get('q') || '').toLowerCase();
    if (q && $$('.pcard').length) {
      $$('.pcard').forEach(function (card) {
        var nameEl = $('.pcard-name', card);
        var name = nameEl ? nameEl.textContent.toLowerCase() : '';
        var li = card.closest('li') || card;
        if (name.indexOf(q) === -1) li.style.display = 'none';
      });
    }
  }

  /* ---------------- LAZY LOAD (data-src → src) ---------------- */
  function lazyImages() {
    var PH = (function () { try { return base() + '/assets/images/placeholder.svg'; } catch (e) { return ''; } })();
    var imgs = $$('.pcard img[data-src], img[data-src]');
    if (!('IntersectionObserver' in window)) {
      imgs.forEach(function (im) { im.src = url(im.getAttribute('data-src')); });
      return;
    }
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (!en.isIntersecting) return;
        var im = en.target;
        var ds = im.getAttribute('data-src');
        if (ds) {
          im.onerror = function () { im.onerror = null; if (PH) im.src = PH; };
          im.src = url(ds);
        }
        var dss = im.getAttribute('data-srcset');
        if (dss) im.setAttribute('srcset', dss);
        im.removeAttribute('data-src');
        io.unobserve(im);
      });
    }, { rootMargin: '300px' });
    imgs.forEach(function (im) { io.observe(im); });
  }

  /* ---------------- BROKEN IMAGE FALLBACK ---------------- */
  function fallbackBroken() {
    var PH = (function () { try { return base() + '/assets/images/placeholder.svg'; } catch (e) { return ''; } })();
    if (!PH) return;
    document.addEventListener('error', function (e) {
      if (e.target.tagName === 'IMG' && e.target.src && !e.target.src.endsWith('placeholder.svg')) {
        e.target.onerror = null;
        e.target.src = PH;
      }
    }, true);
  }

  /* ---------------- ADMIN PRODUCTS SYNC (server local / Supabase) ---------------- */
  function syncAdminProducts() {
    // Rota pública: só produtos com estoque, sem dados sensíveis de clientes/admin
    fetch('/api/public/products')
      .then(function (r) { return r.json(); })
      .then(function (json) {
        if (!json.success || !json.data || !json.data.length) return;
        var map = {};
        var byId = {};
        json.data.forEach(function (p) {
          var pid = p.source_id || p.id; // produtos importados mantêm o ID original do catálogo
          map[pid] = {
            name: p.name,
            price: p.price,
            img: p.image || '',
            url: p.url || '',
            category: p.category
          };
          byId[pid] = p;
        });
        // Re-registra modelos já salvos no carrinho (chaves pid__mid) para
        // o drawer/página do carrinho exibi-los mesmo após recarregar.
        try {
          ['podpahh_cart_v2', 'podpahh_cart_v1'].forEach(function (ck) {
            var cart = {};
            try { cart = JSON.parse(localStorage.getItem(ck)) || {}; } catch (e) { cart = {}; }
            Object.keys(cart).forEach(function (key) {
              if (map[key]) return;
              var sep = key.lastIndexOf('__');
              if (sep < 0) return;
              var p = byId[key.substring(0, sep)];
              if (!p) return;
              var found = null;
              (p.models || []).forEach(function (x) { if (key === (p.source_id || p.id) + '__' + x.id) found = x; });
              if (!found) return;
              var mp = Number(found.price) || 0;
              map[key] = {
                name: p.name + ' — ' + found.name,
                price: mp > 0 ? mp : p.price,
                img: found.image || p.image || '',
                url: '', category: p.category
              };
            });
          });
        } catch (e) {}
        window.PODPAHH_ADMIN_PRODUCTS = map;
        renderAll(); // re-renderiza carrinho/badges com preços atualizados do banco
      })
      .catch(function () { /* servidor offline: segue com catálogo estático */ });
  }

  /* ---------------- MOBILE MENU / SEARCH (substitui o bundle legado) ---------------- */
  function openMobMenu() {
    var d = $('#mobMenuDrawer'), o = $('#mobMenuOverlay'), h = $('#mobHamburger');
    if (d) d.classList.add('open');
    if (o) o.classList.add('open');
    if (h) h.classList.add('active');
    document.body.style.overflow = 'hidden';
  }
  function closeMobMenu() {
    var d = $('#mobMenuDrawer'), o = $('#mobMenuOverlay'), h = $('#mobHamburger');
    if (d) d.classList.remove('open');
    if (o) o.classList.remove('open');
    if (h) h.classList.remove('active');
    document.body.style.overflow = '';
  }
  window.vsMobMenuOpen = function () { openMobMenu(); };
  window.vsMobMenuClose = function () { closeMobMenu(); };
  window.vsMobSearchToggle = function () {
    var bar = $('#mobSearchBar'), toggle = $('#mobSearchToggle');
    if (!bar) return;
    var isOpen = bar.classList.contains('open');
    if (isOpen) {
      bar.classList.remove('open');
      if (toggle) toggle.classList.remove('active');
      document.body.classList.remove('mob-search-open');
    } else {
      bar.classList.add('open');
      if (toggle) toggle.classList.add('active');
      document.body.classList.add('mob-search-open');
      var inp = $('#mobSearchInput');
      if (inp) setTimeout(function () { inp.focus(); }, 120);
    }
  };

  /* ---------------- INIT ---------------- */
  document.addEventListener('DOMContentLoaded', function () {
    scrapeCards();
    ageGate();
    wireSearch();
    lazyImages();
    fallbackBroken();
    renderAll();
    renderWishCount();
    syncWishButtons();
    syncAdminProducts();
    loadWaNumber(); // puxa o número do WhatsApp configurado no painel admin
    // fechar drawer com overlay ja tem onclick; garante ESC
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') toggleCart(false);
    });
  });
})();
